author: Arthur Baghdasaryan
name: Convert string to multiline string
description: This action will split the string by separator
branding:
  icon: feather
  color: white
inputs:
  string:
    description: String to split
    required: true
outputs:
  result:
    description: Action Result
runs:
  using: node16
  main: ./dist/index.js
